### ISSUE TITLE
Support for multiple files

### ISSUE THREAD

**Issue by ndanzi** [leewinder/ng2-file-drop#16]
Hi all,
When will dragging multiple files be available?
I would really love that feature, that would make your module really complete!

thank you very much
Nicolò

**Comment by MRVDOG** [comment]
I second this, I love this module already, but it lacks multiple file support, which is what I'm in need of

**Comment by wlievens** [comment]
Need this too, this would make a great addition!

**Comment by KirillStub** [comment]
Need this too!

**Comment by leewinder** [comment]
Multiple file support in v1.0.0 - Pull request [#28](https://github.com/leewinder/ng2-file-drop/pull/28)
