### ISSUE TITLE
ng2FileDropHoverStart and ng2FileDropHoverEnd missbehaving

### ISSUE THREAD

**Issue by hugodes** [leewinder/ng2-file-drop#17]
Whenever I drag a file onto an element in the two functions get called repeatedly (multiple times per second) one after the other, and because I'm using them to set a cutom style I get a flashing animation.

**Comment by leewinder** [comment]
Could you provide a bit more info please
* Browser (+ version)
* OS

I have noticed that when a file is dragged on I'm now seeing the following behaviour
* ng2FileDropHoverStart called
* ng2FileDropHoverEnd  called
* ng2FileDropHoverStart called

And when it's dragged off, I'm seeing 
* ng2FileDropHoverEnd  called
* ng2FileDropHoverStart called
* ng2FileDropHoverEnd  called

So there does seem to be an issue where start and end is being called before the code settles on start (and the opposite when leaving) which I'll look into, but I'm not seeing it called any more than that.

Can you confirm this is the behaviour you're seeing, or is it different?

Thanks

**Comment by chrsadk** [comment]
Hi,

The behaviour I'm seeing is multiple calls to ng2FileDropHoverStart  and ng2FileDropHoverEnd whenever I'm moving the mouse around in the drop-zone (while dragging a file of course). 

If i keep the mouse still, then the calls stop.

Best regards,
Christian

**Comment by hugodes** [comment]
Closing this issue since the project has moved away from ng2-file-drop. So unfortunately, I cannot get back to you guys on this issue.
