### ISSUE TITLE
Ng2FileDropFilesDropped is not recognized

### ISSUE THREAD

**Issue by SamuelSlf** [leewinder/ng2-file-drop#33]
Hello, when i try import Ng2FileDropFilesDropped in my component i get the error "Has no exported member", but apparently in the documentation is ok.

**Comment by NehalBhandariSlalom** [comment]
I used this Ng2FileDropFiles instead of Ng2FileDropFilesDropped and in the html you have to specify  (ng2FileDropFilesDropped)="dragFilesDropped($event)" and it worked for me.

**Comment by SamuelSlf** [comment]
Thanks @NehalBhandariSlalom !!

**Comment by himasagargit** [comment]
Thanks @NehalBhandariSlalom it works
