### ISSUE TITLE
postinstall tries to call globally installed typings

### ISSUE THREAD

**Issue by mpienkowski** [leewinder/ng2-file-drop#35]
Postinstall in package.json tries to call globally installed typings, due to the fact that typings is listed as a dev-dependency, not a normal dependency. If user (integration server) doesn't have typings installed, npm will fail to install ng2-file-drop. Please move typings to normal dependencies

Thanks!

**Comment by miszo** [comment]
Hi,

I'm also interested. +1

Could you please clarify whether you need typings for ng2-file-drop or tslerp (which is also a dependency).

Thanks

**Comment by tomash89** [comment]
+1 
What is worse, the globally installed _typings_ did not work for me and I had to add it to the dependencies in package.json to make it work. (Side question: I'm new to NPM and this is the first time I've come across it, do you know what might have caused it?)
```
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! tslerp@1.0.5 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the tslerp@1.0.5 postinstall script.
```

**Comment by madoar** [comment]
This problem has already previously been reported by me (see #7 for more details).
I think the best solution to the problem would be if someone opens a PR for it.

**Comment by fabn** [comment]
Also I don't know typings, but when is installed it shows this deprecation warning, 

```
npm WARN deprecated typings@1.5.0: Typings is deprecated in favor of NPM @types -- see README for more information
```

so maybe the best thing could be to get rid of it.

**Comment by leewinder** [comment]
Typings dependency dropped in ng2-file-drop v5.0.0
https://www.npmjs.com/package/ng2-file-drop
