### ISSUE TITLE
accepted-file.ts:5

### ISSUE THREAD

**Issue by exlineo** [leewinder/ng2-file-drop#36]
Strangely, I've this error in console log :
Uncaught TypeError: Cannot read property 'create' of undefined
    at accepted-file.ts:5
Chrome is trying to read a TS file.
Im' working on angular 4.3.6, Typescript 2.4.2, ng2-file-drop 1.1.0 and typing is globaly installed...

Do you have any clue ?

**Comment by leewinder** [comment]
Should be resolved in ng2-file-drop v5.0.0
https://www.npmjs.com/package/ng2-file-drop
