### ISSUE TITLE
New Issue with Angular 4.4.0-RC.0

### ISSUE THREAD

**Issue by xonuzofa** [leewinder/ng2-file-drop#38]
Error: Uncaught (in promise): Error: Unexpected value 'FileDropModule' imported by the module 'FileModule'. Please add a @NgModule annotation.
Error: Unexpected value 'FileDropModule' imported by the module 'FileModule'. Please add a @NgModule annotation.

Did not have this issue before updating angular 4 to 4.4.0-RC.0

**Comment by leewinder** [comment]
The latest version of Angular 4 was added to ng2-file-drop v4.0.0
https://www.npmjs.com/package/ng2-file-drop
