### ISSUE TITLE
Safari Issue: Can't find variable: DragEvent

### ISSUE THREAD

**Issue by andjonno** [leewinder/ng2-file-drop#4]
Tested in Chrome & Firefox and works perfectly, however I'm getting the following error in Safari: 

`Error: (SystemJS) Can't find variable: DragEvent`

Stack Trace: 
`run@http://localhost:3000/node_modules/zone.js/dist/zone.js:114:49
	http://localhost:3000/node_modules/zone.js/dist/zone.js:502:60
	invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:265:40
	runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:154:57
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:401:42
	invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:339:44
	Evaluating http://localhost:3000/node_modules/ng2-file-drop/directives/file-drop.directive.js
	Evaluating http://localhost:3000/node_modules/ng2-file-drop/module/file-drop.module.js
	Evaluating http://localhost:3000/node_modules/ng2-file-drop/index.js
	Evaluating http://localhost:3000/src/js/app.module.js
	Evaluating http://localhost:3000/src/js/main.js
	Error loading http://localhost:3000/src/js/main.js — system.src.js:122:88`

**Comment by andjonno** [comment]
Here is a stack trace
`run@http://localhost:3000/node_modules/zone.js/dist/zone.js:114:49
	http://localhost:3000/node_modules/zone.js/dist/zone.js:502:60
	invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:265:40
	runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:154:57
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:401:42
	invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:339:44
	Evaluating http://localhost:3000/node_modules/ng2-file-drop/directives/file-drop.directive.js
	Evaluating http://localhost:3000/node_modules/ng2-file-drop/module/file-drop.module.js
	Evaluating http://localhost:3000/node_modules/ng2-file-drop/index.js
	Evaluating http://localhost:3000/src/js/app.module.js
	Evaluating http://localhost:3000/src/js/main.js
	Error loading http://localhost:3000/src/js/main.js — system.src.js:122:88`

**Comment by leewinder** [comment]
Hi @andjonno, I will try to have a look at this tonight (UK time).  I assume you are running Safari on Mac OS, or are you running Safari on Windows?

**Comment by andjonno** [comment]
Hey @leewinder , thank you that'd be great! Yes running on macOS Sierra.

**Comment by leewinder** [comment]
Hi @andjonno, pull request merged in and version 0.2.0 release
https://www.npmjs.com/package/ng2-file-drop

Apologies for the delay in this, I just started a new job :)
