### ISSUE TITLE
Compilation error with Angular 5.0.0

### ISSUE THREAD

**Issue by szavoda** [leewinder/ng2-file-drop#40]
When building an Angular 5.0.0 projects that uses ng2-file-drop, I receive the following error:

ERROR in ./node_modules/ng2-file-drop/index.ts
Module build failed: Error: D:\Dev\Jsa\2017\Jsa.Admin\node_modules\ng2-file-drop\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (D:\Dev\Jsa\2017\Jsa.Admin\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (D:\Dev\Jsa\2017\Jsa.Admin\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/shared/shared.module.ts 38:0-50
 @ ./src/app/utilities/utilities.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by burakkilic** [comment]
I am getting the same error.

**Comment by zeljko-bulatovic** [comment]
Same error

**Comment by Lareolan** [comment]
Same issue here.

Does anyone have a workaround until this gets fixed?

**Comment by szavoda** [comment]
I am sure there is a simple fix, but I would imagine you could also just port the code into your own src and it would be fine...

**Comment by ToKaDev** [comment]
Same error here, ist there a fix for it?

**Comment by aerypton** [comment]
Same here....

**Comment by daangeerdink** [comment]
I've switched over to `ngx-file-drop`.

**Comment by eloufirhatim** [comment]
Anyone have a workaround ?

**Comment by aerypton** [comment]
Nope... switched to ngx-file-drop...

**Comment by leewinder** [comment]
Angular 5 support added in ng2-file-drop v5.0.0
https://www.npmjs.com/package/ng2-file-drop

**Comment by venkata82** [comment]
Thanks. Fix is working.
