### ISSUE TITLE
AOT with Angular 5

### ISSUE THREAD

**Issue by lexon0011** [leewinder/ng2-file-drop#41]
AOT compiling with angular 5 raise an error:

![2017-11-02 19_44_55-administrator_ c__windows_system32_cmd exe](https://user-images.githubusercontent.com/16290662/32344284-a4272fc8-c006-11e7-99cd-380e469d2a52.png)

After removing the folder `node_modules\ng2-file-drop\node_modules\@angular` it works. I think the problem are the dependencies in the packages.json.

**Comment by dosama** [comment]
Any news about this issue ???
Is ng2-file-drop is supported in Angular file ???

**Comment by lexon0011** [comment]
Any news?

**Comment by leewinder** [comment]
Angular 5 support added in ng2-file-drop v5.0.0
https://www.npmjs.com/package/ng2-file-drop
