### ISSUE TITLE
Unexpected value 'FileDropModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by reinaldozhang** [leewinder/ng2-file-drop#9]
Hi there. I am having trouble importing this module to my Angular2 web app. Currently I am using webpack as a replacement for systemjs.config.js. Any suggestion on how to solve this problem? Thanks a lot.

**Comment by leewinder** [comment]
Hopefully this is resolved in v1.0.0 - Pull request [#28](https://github.com/leewinder/ng2-file-drop/pull/28)
